name: cityfix_mobile
description: CityFix – Urban Civic Issue Reporting for Jimma City, Ethiopia.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Networking
  dio: ^5.4.3+1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3

  # Local Storage (manual adapters – no hive_generator needed)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location & Media
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2

  # UI Helpers
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1

  # Connectivity
  connectivity_plus: ^6.0.3

  # Utilities
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  socket_io_client: ^3.1.4
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
